name : Minecraft_Survival_Plugin
main: fr.minecraft.survival.plugin.main.PluginMain
version: 0.01
commands:
  points:
    description: A command that make you see your own number of points

  sethome:
  delhome:
  home:
  bet:
    description: A command to bid during an ongoing auction.
  vanish:
    description: A command that vanish a specific player.
